server:
  port: 8084

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: visited.places.224@gmail.com
    password: trxg bdti xalj nccg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notification:
  email:
    from: visited.places.224@gmail.com

logging:
  level:
    com.medplatform: DEBUG