server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service-auth
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/**

          - id: user-service-doctors
            uri: http://localhost:8081
            predicates:
              - Path=/api/doctors/**

          - id: user-service-institutions
            uri: http://localhost:8081
            predicates:
              - Path=/api/institutions/**

          - id: appointment-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/appointments/**

          - id: appointment-schedules
            uri: http://localhost:8082
            predicates:
              - Path=/api/schedules/**

          - id: medical-records-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/medical-records/**

          - id: notification-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/notifications/**

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG