server:
  port: 8083

spring:
  application:
    name: medical-records-service
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongodb}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:medical_records_db}
      username: ${SPRING_DATA_MONGODB_USERNAME:root}
      password: ${SPRING_DATA_MONGODB_PASSWORD:root}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: medical-records-service
      auto-offset-reset: earliest

logging:
  level:
    com.medplatform: DEBUG

jwt:
  secret: ${JWT_SECRET:medplatform-super-secret-key-2024-very-long-string}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
