server:
  port: 8083

spring:
  application:
    name: medical-records-service

  data:
    mongodb:
      uri: mongodb://root:root@mongodb:27017/medical_records_db?authSource=admin

logging:
  level:
    com.medplatform: DEBUG
